---
- src: geerlingguy.nginx
  version: 1.7.0

- src: geerlingguy.php
  version: 1.8.2

- src: geerlingguy.mysql
  version: 2.0.1

- src: geerlingguy.mailhog
  version: 1.0.5

- src: geerlingguy.composer
  version: 1.3.0
